<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LmcUserImpersonate\Module'                                               => __DIR__ . '/Module.php',
  'LmcUserImpersonate\Controller\Admin'                                     => __DIR__ . '/src/LmcUserImpersonate/Controller/Admin.php',
  'LmcUserImpersonate\Controller\User'                                      => __DIR__ . '/src/LmcUserImpersonate/Controller/User.php',
  'LmcUserImpersonate\Exception\Domain'                                     => __DIR__ . '/src/LmcUserImpersonate/Exception/Domain.php',
  'LmcUserImpersonate\Exception\NotImpersonating'                           => __DIR__ . '/src/LmcUserImpersonate/Exception/NotImpersonating.php',
  'LmcUserImpersonate\Exception\UserNotFound'                               => __DIR__ . '/src/LmcUserImpersonate/Exception/UserNotFound.php',
  'LmcUserImpersonate\Exception\UserNotLoggedIn'                            => __DIR__ . '/src/LmcUserImpersonate/Exception/UserNotLoggedIn.php',
  'LmcUserImpersonate\Exception\LmcUserImpersonate'                         => __DIR__ . '/src/LmcUserImpersonate/Exception/LmcUserImpersonate.php',
  'LmcUserImpersonate\Module\AbstractModule'                                => __DIR__ . '/src/LmcUserImpersonate/Module/AbstractModule.php',
  'LmcUserImpersonate\ModuleManager\Feature\AutoloaderProviderDefaultTrait' => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/AutoloaderProviderDefaultTrait.php',
  'LmcUserImpersonate\ModuleManager\Feature\ClassDirTrait'                  => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/ClassDirTrait.php',
  'LmcUserImpersonate\ModuleManager\Feature\ClassNamespaceTrait'            => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/ClassNamespaceTrait.php',
  'LmcUserImpersonate\ModuleManager\Feature\ConfigProviderTrait'            => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/ConfigProviderTrait.php',
  'LmcUserImpersonate\ModuleManager\Feature\ControllerConfigProviderTrait'  => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/ControllerConfigProviderTrait.php',
  'LmcUserImpersonate\ModuleManager\Feature\ServiceConfigProviderTrait'     => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/ServiceConfigProviderTrait.php',
  'LmcUserImpersonate\ModuleManager\Feature\ViewHelperConfigProviderTrait'  => __DIR__ . '/src/LmcUserImpersonate/ModuleManager/Feature/ViewHelperConfigProviderTrait.php',
  'LmcUserImpersonate\Options\ModuleOptions'                                => __DIR__ . '/src/LmcUserImpersonate/Options/ModuleOptions.php',
  'LmcUserImpersonate\Service\User'                                         => __DIR__ . '/src/LmcUserImpersonate/Service/User.php',
  'LmcUserImpersonate\View\Helper\LmcUserImpersonatorDisplayName'           => __DIR__ . '/src/LmcUserImpersonate/View/Helper/LmcUserImpersonatorDisplayName.php',
  'LmcUserImpersonate\View\Helper\LmcUserImpersonatorIdentity'              => __DIR__ . '/src/LmcUserImpersonate/View/Helper/LmcUserImpersonatorIdentity.php',
);
